# Generated by Django 5.1 on 2024-09-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruedas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='precio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
