# Generated by Django 5.1 on 2024-09-10 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruedas', '0002_unidad_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ruedas.unidad')),
            ],
        ),
    ]
