# Generated by Django 5.1 on 2024-09-11 00:04

import ruedas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruedas', '0003_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='media/', validators=[ruedas.models.validate_image]),
        ),
    ]
