# Generated by Django 5.1 on 2024-09-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruedas', '0006_alter_imagen_options_unidad_anio_alter_unidad_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='precio',
            field=models.IntegerField(blank=True, max_length=25, null=True),
        ),
    ]
