# Generated by Django 5.1 on 2024-09-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruedas', '0008_alter_unidad_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
