# Generated by Django 5.1 on 2024-09-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruedas', '0009_alter_unidad_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='motor',
        ),
        migrations.AddField(
            model_name='unidad',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unidad',
            name='version',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='anio',
            field=models.IntegerField(choices=[(2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], default=2024, verbose_name='año'),
        ),
    ]
