# Generated by Django 5.1 on 2024-09-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruedas', '0010_remove_unidad_motor_unidad_modelo_unidad_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='kilometros',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
